#!/bin/sh

prog=dome
width=150
height=75
size=${width}x${height}

screensize=`xdpyinfo | awk '/dimensions:/ { print $2 }'`
screenwidth=`echo $screensize | cut -dx -f1`

xslop=10
yslop=20
yoff=50

pids=""

layer() {
    l=$1; shift
    n=$1; shift
    id=$1; shift

    x=`expr \( $screenwidth / 2 \) - \( \( $n \* \( $width + $xslop \) \) / 2 \)`
    y=`expr $l \* \( $height + $yslop \) + $yoff`

    while [ $n -ne 0 ]; do
	p=""
	if [ ! -z "$1" ]; then
	    p=`echo $1 | sed -e 's,[0-9]*,-p&,g'`
	fi
	shift
	cmd="test-$prog -geometry ${width}x${height}+$x+$y -s$id $p"
	echo $cmd
	$cmd &
	pids="$pids $!"
	x=`expr $x + $width + $xslop`
	id=`expr $id + 1`
	n=`expr $n - 1`
    done
}

trap 'kill $pids' term int

make test-$prog

#     layer
#     | number
#     | | startid
#layer 0 1 1     "2 3"
#layer 1 2 2  "4 5" "5 6"
#layer 2 3 4    7 "10 11" 8
#layer 3 2 7     9 9
#layer 4 1 9      1
#layer 5 2 10    4 6

layer 0 5  1 "2 6" "1 3 7" "2 4 8" "3 5 9" "4 10"
layer 1 5  6 "7 1 11" "6 8 2 12" "7 9 3 13" "8 10 4 14" "9 5 15"
layer 2 5 11 "12 6 16" "11 13 7 17" "12 14 8 18" "13 15 9 19" "14 10 20"
layer 3 5 16 "17 11 21" "16 18 12 22" "17 19 13 23" "18 20 14 24" "19 15 25"
layer 4 5 21 "16 22" "21 23 17" "22 24 18" "23 25 19" "24 20"

wait
